### ISSUE TITLE
Css das paginas nos comentários precisa de revisão

### ISSUE THREAD

**Issue by GGomes08** [Samuel123456-stack/PI4Konex_AgendaPontual#2]
Samuel os botões de suas telas estavam button ou com input do tipo button, eu os mudei para o input do tipo de submit, com isso peço que atualize o css das seguintes paginas 

**tela_agendamento** 
**tela_consRecep**
**tela_proconfirmation**
**tela_updateSchedule**

**Comment by Samuel123456-stack** [comment]
Olá, Gustavo. Para o seu conhecimento, já atualizei as telas, conforme solicitado

**Comment by GGomes08** [comment]
Olá, Agradecido Samuel.
